version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Mapeie a porta 8080 do host para a porta 80 do contêiner
    volumes:
      - .:/var/www/html # Monte o diretório do projeto no contêiner
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: laravel_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}